### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by walsht** [netmaid/GoogleAnalytics#1]
I stumbled upon this and looking to use with Carthage.  Can you add the tagged version?  Then I can use for Carthage.

Thank you, Tim

**Comment by walsht** [comment]
Actually, I can get past this by specifying the branch in the cart file 

```
github "netmaid/GoogleAnalytics" "master"
```

Ran into this...

```
Dependency "GoogleAnalytics" has no shared framework schemes
```

**Comment by netmaid** [comment]
I will consider to support Carthage.
Thanks, your comment.

**Comment by netmaid** [comment]
Sorry for my laziness. Can you try again?

**Comment by walsht** [comment]
Looks good, thanks.
